# Generated by Django 4.2.7 on 2024-01-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='mech_toughness_min',
            new_name='mech_toughness_single',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='supp_mech_toughness_min',
            new_name='supp_mech_toughness_single',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='mech_toughness_min',
            new_name='mech_toughness_single',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='supp_mech_toughness_min',
            new_name='supp_mech_toughness_single',
        ),
    ]
