# Generated by Django 4.2.7 on 2023-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0002_institution_alter_material_chem_al_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='mech_toughness_1',
        ),
        migrations.RemoveField(
            model_name='material',
            name='mech_toughness_2',
        ),
        migrations.RemoveField(
            model_name='material',
            name='mech_toughness_3',
        ),
        migrations.AddField(
            model_name='material',
            name='mech_toughness_mean',
            field=models.IntegerField(blank=True, null=True, verbose_name='Average'),
        ),
        migrations.AddField(
            model_name='material',
            name='mech_toughness_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_hardness_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hardness, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_hardness_units',
            field=models.CharField(blank=True, choices=[('HB', 'Brinell'), ('HV', 'Vickers'), ('HRC', 'Rockwell C'), ('HRB', 'Rockwell B'), ('HRA', 'Rockwell A')], default='HB', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_toughness_size',
            field=models.CharField(blank=True, choices=[('10x10', '10x10'), ('7.5x10', '7.5x10'), ('5x10', '5x10'), ('2.5x10', '2.5x10')], default='10x10', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_toughness_units',
            field=models.CharField(blank=True, choices=[('J', 'Joule')], default='J', max_length=20, null=True),
        ),
    ]
