# Generated by Django 5.0 on 2023-12-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0007_remove_certificate_chem_al_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='specifications',
            name='institution',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mpct_app.specification'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
