# Generated by Django 5.0 on 2023-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0008_specification_remove_specifications_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
