# Generated by Django 5.0 on 2023-12-13 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0009_certificate_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='chem_al_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aluminum, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_b_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Boron, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_c_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbon, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ca_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calcium, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_co_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cobalt, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_cr_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chromium, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_cu_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Copper, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_fe_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iron, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_mn_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manganese, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_mo_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Molybdenum, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_n_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nitrogen, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_nb_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Niobium, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ni_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nickel, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_p_min',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phosphorus, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_s_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sulfur min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_si_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ti_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Titanium, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_v_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vanadium, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_w_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tungsten, min'),
        ),
    ]
