# Generated by Django 5.0 on 2023-12-25 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpct_app', '0012_alter_certificate_heat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='supp_ddwt',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='supp_scct',
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supp_ddwt',
        ),
        migrations.RemoveField(
            model_name='material',
            name='supp_scct',
        ),
        migrations.AddField(
            model_name='certificate',
            name='supp_dwtt',
            field=models.BinaryField(blank=True, null=True, verbose_name='Drop Weight  Tear Test'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='supp_ssc',
            field=models.BinaryField(blank=True, null=True, verbose_name='Sulfide Stress Corrosion test'),
        ),
        migrations.AddField(
            model_name='material',
            name='supp_dwtt',
            field=models.BinaryField(blank=True, null=True, verbose_name='Drop Weight  Tear Test'),
        ),
        migrations.AddField(
            model_name='material',
            name='supp_ssc',
            field=models.BinaryField(blank=True, null=True, verbose_name='Sulfide Stress Corrosion test'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_al_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aluminum, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_b_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Boron, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_c_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbon, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_ca_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calcium, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_co_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cobalt, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_cr_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chromium, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_cu_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Copper, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_fe_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iron, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_mn_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manganese, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_mo_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Molybdenum, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_n_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nitrogen, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_nb_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Niobium, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_ni_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nickel, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_p_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phosphorus, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_p_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phosphorus, min'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_s_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sulfur max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_si_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silicon, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_si_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silicon, min'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_ti_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Titanium, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_v_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vanadium, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='chem_w_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tungsten, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_hardness_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hardness, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_tensile_strength_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TS, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_tensile_strength_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TS, min'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_toughness_mean',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Impact Test, Average'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_toughness_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Impact Test, Minimum'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_yield_strength_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='YS, max'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mech_yield_strength_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='YS, min'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='supp_mech_toughness_mean',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Supplementary Impact Test, Aver.'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='supp_mech_toughness_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Supplementary Impact Test, Min.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_al_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aluminum, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_b_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Boron, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_c_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carbon, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ca_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calcium, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_co_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cobalt, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_cr_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Chromium, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_cu_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Copper, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_fe_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Iron, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_mn_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Manganese, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_mo_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Molybdenum, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_n_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nitrogen, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_nb_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Niobium, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ni_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nickel, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_p_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phosphorus, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_p_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Phosphorus, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_s_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sulfur max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_si_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silicon, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_si_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Silicon, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_ti_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Titanium, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_v_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vanadium, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_w_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tungsten, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_hardness_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hardness, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_tensile_strength_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TS, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_tensile_strength_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='TS, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_toughness_mean',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Impact Test, Average'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_toughness_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Impact Test, Minimum'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_yield_strength_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='YS, max'),
        ),
        migrations.AlterField(
            model_name='material',
            name='mech_yield_strength_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='YS, min'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supp_mech_toughness_mean',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Supplementary Impact Test, Aver.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supp_mech_toughness_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Supplementary Impact Test, Min.'),
        ),
    ]
